---
services:
  stirling-pdf:
    image: "frooodle/s-pdf:latest"
    container_name: "stirling-pdf"
    restart: "unless-stopped"
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      SECURITY_CSRFDISABLED: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      LANGS: "en_GB,en_US,fr_FR"
      SYSTEM_SHOWUPDATE: "true"
      SYSTEM_SHOWUPDATEONLYADMIN: "true"
      METRICS_ENABLE: "false"
      UI_APPNAME: "Stirling PDF"
      UI_HOMEDESCRIPTION: "Your locally hosted one-stop-shop for all your PDF needs."
      UI_APPNAMENAVBAR: "Stirling PDF"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/training-data:/usr/share/tessdata" # Required for extra OCR languages
      - "./config/extra:/configs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`stirling-pdf.${DOMAIN}`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
    networks:
      - "proxy"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://127.0.0.1:8080/ | grep -qv 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16

networks:
  proxy:
    external: "true"
