#!/usr/bin/env bash

commands=$(cat <<EOF

# Generated by configuration script from https://github.com/etiennecollin/homelab
alias dcu="docker compose --env-file ../secret.env up -d --force-recreate"
alias lag="lazygit"
alias lad="lazydocker"
EOF
)

echo "$commands" >> ~/.bashrc
echo "$commands" >> ~/.zshrc
