---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- datetime:
    text_size: "xl"
    format:
      dateStyle: "long"
      timeStyle: "short"
      hour12: "false"

- resources:
    cpu: "true"
    memory: "true"
    cputemp: "true"
    tempmin: "0"
    tempmax: "100"
    uptime: "false"
    units: "metric"
    refresh: "3000" # in ms

- search:
    provider: "duckduckgo"
    focus: "true"
    showSearchSuggestions: "false"
    target: "_blank"

- openmeteo:
    label: "{{HOMEPAGE_VAR_CITY}}"
    timezone: "{{HOMEPAGE_VAR_TIMEZONE}}"
    units: "metric"
    cache: "5"
    format:
      maximumFractionDigits: "1"
