---
services:
  ntfy:
    image: "binwiederhier/ntfy"
    container_name: "ntfy"
    restart: "unless-stopped"
    command:
      - "serve"
    environment:
      TZ: ${TIMEZONE}
      NTFY_BASE_URL: "https://ntfy.${DOMAIN}"
      NTFY_ATTACHMENT_CACHE_DIR: "/var/lib/ntfy/attachments"
      NTFY_ATTACHMENT_FILE_SIZE_LIMIT: "25M"
      NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT: "5G"
      NTFY_ATTACHMENT_EXPIRY_DURATION: "5h"
      # NTFY_ENABLE_LOGIN: "true"
      # NTFY_AUTH_FILE: "/var/lib/ntfy/auth.db"
      # NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
      NTFY_BEHIND_PROXY: "true"
      NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh" # For IOS notifications
    volumes:
      - "./cache:/var/cache/ntfy"
      # - "./config:/etc/ntfy"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://127.0.0.1:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: "60s"
      timeout: "10s"
      retries: "3"
      start_period: "40s"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.${DOMAIN}`)"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
    networks:
      - "proxy"

networks:
  proxy:
    external: "true"
