NUT_SERVERS:
  - HOST: "nut-upsd"
    PORT: "3493"
    USERNAME: "upsmon"
    PASSWORD: "supersecretpassword1234"
INFLUX_HOST: ""
INFLUX_TOKEN: ""
INFLUX_ORG: ""
INFLUX_BUCKET: ""
INFLUX_INTERVAL: "10"
DATE_FORMAT: "YYYY/MM/DD"
TIME_FORMAT: "24-hour"
DASHBOARD_SECTIONS:
  - key: "KPIS"
    enabled: "true"
  - key: "CHARTS"
    enabled: "true"
  - key: "VARIABLES"
    enabled: "true"
DISABLE_VERSION_CHECK: "false"
