services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Web interface HTTP/HTTPS Port
      - "8080:80/tcp"
      - "4443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      TZ: ${TIMEZONE}
      FTLCONF_dns_domain: ${DOMAIN}
      FTLCONF_dns_listeningMode: "all" # Since we use the Docker's default `bridge` network
      FTLCONF_dns_queryLogging: "false"
      FTLCONF_misc_privacylevel: "3"
      FTLCONF_dns_upstreams: "9.9.9.11;149.112.112.11" # Quad9 Filtered, ECS enabled
    env_file:
      - "./secret.env"
    volumes:
      - "./config/etc-pihole:/etc/pihole"
    cap_add:
      - SYS_NICE # To upgrade process priority
      # - NET_ADMIN # Required to use Pi-hole as DHCP server
    restart: unless-stopped
