services:
  pihole:
    image: "pihole/pihole:2025.07.1"
    container_name: "pihole"
    hostname: "pihole"
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    env_file:
      - "./secret.env"
    environment:
      FTLCONF_dns_dnssec: "true"
      FTLCONF_dns_domain: "${DOMAIN}"
      FTLCONF_dns_listeningMode: "all" # Since we use the Docker's default `bridge` network
      FTLCONF_dns_queryLogging: "false"
      FTLCONF_dns_upstreams: "9.9.9.11;149.112.112.11" # Quad9 Filtered, DNSSEC, ECS enabled
      FTLCONF_misc_privacylevel: "3"
      PIHOLE_GID: "${PGID}"
      PIHOLE_UID: "${PUID}"
      TZ: "${TIMEZONE}"
    dns:
        - "127.0.0.1"
        - "9.9.9.11"
        - "149.112.112.11"
    volumes:
      - "./config/etc-pihole:/etc/pihole"
      - "./config/adlists.list:/etc/pihole/adlists.list:ro"
    cap_add:
      - "SYS_NICE" # To upgrade process priority
      # - NET_ADMIN # Required to use Pi-hole as DHCP server
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.routers.pihole.middlewares=pihole-add-admin@docker"
      - "traefik.http.middlewares.pihole-add-admin.redirectregex.regex=pihole.${DOMAIN}/$$"
      - "traefik.http.middlewares.pihole-add-admin.redirectregex.replacement=pihole.${DOMAIN}/admin/"
      - "traefik.http.middlewares.pihole-add-admin.redirectregex.permanent=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      - "proxy"

networks:
  proxy:
    external: "true"
