---
services:
  ddclient:
    image: "lscr.io/linuxserver/ddclient:4.0.0"
    container_name: "ddclient"
    network_mode: "bridge"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pgrep ddclient >/dev/null || exit 1",
        ]
      interval: "60s"
      timeout: "10s"
      retries: "3"
      start_period: "40s"
    volumes:
      - "./config:/config"
    restart: "unless-stopped"
