---
services:
  sablier:
    image: "acouvreur/sablier:1.7.0"
    container_name: "sablier"
    restart: "unless-stopped"
    command:
      - "start"
      - "--provider.name=docker"
    expose:
      - "10000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      DOCKER_HOST: "tcp://socket-proxy:2375"
    labels:
      - "traefik.enable=true"
    networks:
      - "proxy"
      - "socket-proxy"

networks:
  proxy:
    external: "true"
  socket-proxy:
    external: "true"
