---
services:
  peanut:
    container_name: "peanut"
    image: "brandawg93/peanut:6.0.0"
    volumes:
      - "./config:/config"
    restart: "unless-stopped"
    networks:
      - "proxy"
      - "peanut"
    environment:
      AUTH_DISABLED: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.peanut.rule=Host(`peanut.${DOMAIN}`)"
      - "traefik.http.services.peanut.loadbalancer.server.port=8080"

networks:
  proxy:
    external: "true"
  peanut:
    name: "peanut"
    driver: "bridge"
