---
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:1.23.16"
    container_name: "uptime-kuma"
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TIMEZONE}"
    volumes:
      - "./data:/app/data"
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.${DOMAIN}`)"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    dns:
      - "${MAIN_DNS}"
    networks:
      - "proxy"

networks:
  proxy:
    external: "true"
