---
services:
  traefik:
    image: "traefik:v3.1.2"
    container_name: "traefik"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443"
      # - "443:443/tcp" # Uncomment if you want HTTP3
      # - "443:443/udp" # Uncomment if you want HTTP3
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/config.yaml:/config.yaml:ro"
      - "./config/acme.json:/acme.json"
    environment:
      DOMAIN: ${DOMAIN}
      PUBLIC_EMAIL: ${PUBLIC_EMAIL}
    env_file:
      - "./secret.env"
      - "./traefik.env"
    labels:
      - "traefik.enable=true"
    networks:
      - "proxy"

networks:
  proxy:
    external: "true"
