---
services:
  traefik:
    image: "traefik:v3.3.3"
    container_name: "traefik"
    restart: "unless-stopped"
    depends_on:
      socket-proxy:
        condition: "service_started"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443"
      # - "443:443/tcp" # Uncomment if you want HTTP3
      # - "443:443/udp" # Uncomment if you want HTTP3
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/config.yaml:/config.yaml:ro"
      - "./config/acme.json:/acme.json"
    environment:
      DOMAIN: ${DOMAIN}
      PUBLIC_EMAIL: ${PUBLIC_EMAIL}
    env_file:
      - "./secret.env"
      - "./traefik.env"
    labels:
      - "traefik.enable=true"
    networks:
      - "proxy"
      - "socket-proxy"

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: "socket-proxy"
    restart: "unless-stopped"
    expose:
      - "2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      CONTAINERS: "1"
      ALLOW_START: "1"
      ALLOW_STOP: "1"
      ALLOW_RESTARTS: "1"
    networks:
      - "socket-proxy"
    read_only: "true"
    tmpfs:
      - "/run"

networks:
  proxy:
    external: "true"
  socket-proxy:
    external: "true"
