---
services:
  traefik:
    image: "traefik:v3.5.0"
    container_name: "traefik"
    restart: "unless-stopped"
    depends_on:
      socket-proxy:
        condition: "service_started"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/config.yaml:/config.yaml:ro"
      - "./config/acme.json:/acme.json"
    environment:
      DOMAIN: "${DOMAIN}"
      PUBLIC_EMAIL: "${PUBLIC_EMAIL}"
    env_file:
      - "./secret.env"
      - "./traefik.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard.service=dashboard@internal"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
    networks:
      - "proxy"
      - "socket-proxy"

  socket-proxy:
    image: "lscr.io/linuxserver/socket-proxy:3.2.3"
    container_name: "socket-proxy"
    restart: "unless-stopped"
    expose:
      - "2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      CONTAINERS: "1"
      IMAGES: "1"
      VERSION: "1"
      ALLOW_START: "1"
      ALLOW_STOP: "1"
      ALLOW_RESTARTS: "1"
    networks:
      - "socket-proxy"
    read_only: "true"
    tmpfs:
      - "/run"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries 1 --spider http://socket-proxy:2375/version || exit 1",
        ]
      interval: "60s"
      timeout: "10s"
      retries: "3"
      start_period: "40s"

networks:
  proxy:
    external: "true"
  socket-proxy:
    external: "true"
